### ISSUE TITLE
部分网页截图滚动条存在问题

### ISSUE THREAD

**Issue by Caihaolunnju** [Caihaolunnju/NotePI#10]
如百度，google首页，而且如果重复点击保存截图按钮，截图会重复错位叠加，错位貌似刚好是滚动条的宽度，错误的截图保存在公共测试账号中。

**Comment by luminocean** [comment]
我的windows上没重现出来。。你更新一下看看？

**Comment by Caihaolunnju** [comment]
可能是帐号里遗留了原来的截图导致的问题，我把drive里的数据清了就OK了，没有问题
