### ISSUE TITLE
网页与截图同步似乎只有最上部分网页可以同步

### ISSUE THREAD

**Issue by Caihaolunnju** [Caihaolunnju/NotePI#12]
对于长网页，拉到下面进行笔迹，两边不能同步。

**Comment by luminocean** [comment]
原因：
note.js在截图页面加载完图片之前初始化了。
当图片很大的时候，在它加载完之前页面是空的。
如果这个时候note.js初始化，要拿当前页面的大小来确定画板的大小，那么它拿到的只是空页面的大小，也即当前可视区域的大小。
这样的话，当图片加载完成，实际的大小就会脱离截图页面的画板区域，也就不会把网页下面的笔记进行同步了。
换句话说，截图页面上的画板太小了。

已解决。
