### ISSUE TITLE
forEach异步调用

### ISSUE THREAD

**Issue by MrRiddle** [Caihaolunnju/NotePI#9]
Array.forEach需要传入异步调用函数，
我担心滥用这个方法会带来问题。
如：

pathstring = "";
pathInfo.pathArray.forEach(function (element){
    pathstring += element;
});
path = paper.path(pathstring).attr('stroke',pathInfo.color).attr("stroke-width",pathInfo.width);

pathstring的值似乎是无法确定的。

**Comment by xuqiangm** [comment]
你是说forEach()里面的函数是异步调用的？

**Comment by MrRiddle** [comment]
虽然查阅的资料表示Array.forEach方法是同步调用
不过还是有些担心。
